id: A8437060F
title: f000A
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 21:16:22.654890
  last_modified_at: 2022-05-27 21:16:22.654898
