id: A8437060F
title: f245A
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 21:16:22.850028
  last_modified_at: 2022-05-27 21:16:22.850031
