id: A8437060F
title: f43B8
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 21:16:23.050593
  last_modified_at: 2022-05-27 21:16:23.050595
