id: A8437060F
title: fF46F
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 21:16:24.644878
  last_modified_at: 2022-05-27 21:16:24.644881
